/* Generated By:JJTree: Do not edit this line. ASTAssign.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

import semantic.*;

public
class ASTAssign extends SimpleNode {

  public String lhsIdentifier;

  public ASTAssign(int id) {
    super(id);
  }

  public ASTAssign(Jmm p, int id) {
    super(p, id);
  }

  @Override
  public void checkNodeSemantic() {
    //check if rhs variable exists
    STO lhs = this.symbolTable.doesSymbolExist(this.lhsIdentifier, this.scope);
    if (lhs == null) {
      System.out.println("Variable " + this.lhsIdentifier + " was not declared");
    }

    //check, if a variable is being assigned to the other, that their types match
    SimpleNode rhsNode;
    if (this.children != null) {
      rhsNode = (SimpleNode) this.children[0];
      if (rhsNode.toString().equals("Identifier")) {
        STO rhs = this.symbolTable.doesSymbolExist(((ASTIdentifier) rhsNode).getIdentifier(), this.scope);

        if (rhsNode.children != null) {
          if (((SimpleNode) rhsNode).children[0].toString().equals("ArrayIndex") && lhs.getType() != "int") {
            System.out.println("Cannot assign variable " + ((ASTIdentifier) rhsNode).getIdentifier() + " of type " + rhs.getType() + " to variable " + this.lhsIdentifier + " of type " + lhs.getType());
          } else if (((SimpleNode) rhsNode).children[0].toString().equals("Length")) {
            // ??
          } else if (((SimpleNode) rhsNode).children[0].toString().equals("Call")) {
            //if function external to the class, assume it's correct and ignore
            STFunction functionBeingCalled = this.symbolTable.doesFunctionExist(((ASTCall) rhsNode.children[0]).getValue());
            if (functionBeingCalled != null) {
              //check if variable is of type [class] TODO
              if (functionBeingCalled.getReturn().getType() != lhs.getType()) {
                System.out.println("Return type for function " + ((ASTCall) rhsNode.children[0]).getValue() + " not compatible with variable " + this.lhsIdentifier + " of type " + lhs.getType());
              }
            }
            
          }
          return;
        } 
        if (rhs != null && lhs.getType() != rhs.getType()) {
          System.out.println("Cannot assign variable " + ((ASTIdentifier) rhsNode).getIdentifier() + " of type " + rhs.getType() + " to variable " + this.lhsIdentifier + " of type " + lhs.getType());
        }
      }
    } 

  }

  public void dump(String prefix) {
    System.out.println(toString(prefix) + ": " + this.lhsIdentifier);
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + "    ");
        }
      }
    }
  }

}
/* JavaCC - OriginalChecksum=42171107bb3b507a7e69d9c464358f53 (do not edit this line) */
