/* Generated By:JJTree: Do not edit this line. ASTArrayIndex.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

import org.w3c.dom.Node;

public
class ASTArrayIndex extends SimpleNode {
  public ASTArrayIndex(int id) {
    super(id);
  }

  public ASTArrayIndex(Jmm p, int id) {
    super(p, id);
  }

  @Override
  public String getReturnType() {
    return "int";
  }

  @Override
  public void checkNodeSemantic() {
    if(!((SimpleNode) this.jjtGetChild(0)).getReturnType().equals("int")){
      super.printSemanticError("Array index must be of type int");
      return;
    }
  }

}
/* JavaCC - OriginalChecksum=63f0b766d05a0bd31b56c0214cb0bc26 (do not edit this line) */
