/* Generated By:JJTree: Do not edit this line. ASTArrayAssign.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

import semantic.*;

public
class ASTArrayAssign extends SimpleNode {

  public String lhsIdentifier;

  public ASTArrayAssign(int id) {
    super(id);
    this.actualReturnType = "int[]";
  }

  public ASTArrayAssign(Jmm p, int id) {
    super(p, id);
    this.actualReturnType = "int[]";
  }

  @Override
  public String getReturnType() {
    return this.actualReturnType;
  }

  @Override
  public String getActualReturnType() {
    return this.actualReturnType;
  }

  @Override
  public void checkNodeSemantic() {
    STO lhs = SimpleNode.symbolTable.doesSymbolExist(this.lhsIdentifier, this.scope);
    if (lhs == null) {
      super.printSemanticError("Variable " + this.lhsIdentifier + " was not declared");
    }
    
    if(!((SimpleNode) this.jjtGetChild(0)).getReturnType().equals("int")) {
      super.printSemanticError("Variable types not compatible");
    }
  }

  public void dump(String prefix) {
    System.out.println(toString(prefix) + ": " + this.lhsIdentifier);
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + "    ");
        }
      }
    }
  }

}
/* JavaCC - OriginalChecksum=17942b7bfb170b43eb29e6d2f58836be (do not edit this line) */
