/* Generated By:JJTree: Do not edit this line. ASTArguments.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTArguments extends SimpleNode {
  public ASTArguments(int id) {
    super(id);
  }

  public ASTArguments(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5949bf3f11b48986b36a23df4eb4d583 (do not edit this line) */
