/* Generated By:JJTree: Do not edit this line. ASTArray.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTArray extends SimpleNode {
  public ASTArray(int id) {
    super(id);
  }

  public ASTArray(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2bed2b97c15d5d8b80073a975e696dde (do not edit this line) */
