/* Generated By:JJTree: Do not edit this line. ASTBooleanLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTBooleanLiteral extends SimpleNode {

  protected String booleanValue;

  public ASTBooleanLiteral(int id) {
    super(id);
    this.actualReturnType = "boolean";
  }

  public ASTBooleanLiteral(Jmm p, int id) {
    super(p, id);
    this.actualReturnType = "boolean";
  }

  public String getBooleanValue() {
    return this.booleanValue;
  }

  public void setBooleanValue(String booleanValue){
    this.booleanValue = booleanValue;
  }

  @Override
  public String getReturnType() {
    //since it's a literal, it can't have child nodes, meaning the actual return type of the node matches the return type
    return this.actualReturnType;
  }

  public String toString() {
    return this.booleanValue;
  }

}
/* JavaCC - OriginalChecksum=705d423d898b19d6be77a506856655fb (do not edit this line) */
