/* Generated By:JJTree: Do not edit this line. ASTCondition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCondition extends SimpleNode {
  public ASTCondition(int id) {
    super(id);
  }

  public ASTCondition(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=69d0e3cf45787dde505033fffedd41a4 (do not edit this line) */
