/* Generated By:JJTree: Do not edit this line. ASTExpressionNR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTExpressionNR extends SimpleNode {
  public ASTExpressionNR(int id) {
    super(id);
  }

  public ASTExpressionNR(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7ffd940abccd376edf1fd22e2219d3d6 (do not edit this line) */
