/* Generated By:JJTree: Do not edit this line. ASTFalse.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFalse extends SimpleNode {
  public ASTFalse(int id) {
    super(id);
  }

  public ASTFalse(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b43918bc54c162cd11a460f6a84c4ecc (do not edit this line) */
