/* Generated By:JJTree: Do not edit this line. ASTIf.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTIf extends SimpleNode {

  static int counter = 0;
  int labelId;

  public ASTIf(int id) {
    super(id);
    this.labelId = counter;
    counter++;
  }

  public ASTIf(Jmm p, int id) {
    super(p, id);
    this.labelId = counter;
    counter++;
  }

  public int getLabelId() {
    return this.labelId;
  }

}
/* JavaCC - OriginalChecksum=8daaa5bc763e4edb92ca8561e24fa6ae (do not edit this line) */
