/* Generated By:JJTree: Do not edit this line. ASTLtNR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;public


class ASTLtNR extends SimpleNode {
  public ASTLtNR(int id) {
    super(id);
  }

  public ASTLtNR(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=876401860944942193bb797a9e07c64c (do not edit this line) */
