/* Generated By:JJTree: Do not edit this line. ASTMethodArgument.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMethodArgument extends SimpleNode {

  protected String identifier;
  public String type;

  public ASTMethodArgument(int id) {
    super(id);
  }

  public ASTMethodArgument(Jmm p, int id) {
    super(p, id);
  }

  public String getIdentifier() {
    return this.identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public String getType() {
    return this.type;
  }

  public void dump(String prefix) {
    System.out.println(toString(prefix) + ": type: " + this.type);
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + "    ");
        }
      }
    }
  }

}
/* JavaCC - OriginalChecksum=2a4ad6cdde0349a884c22866cd0718b4 (do not edit this line) */
