/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMult extends SimpleNode {
  public ASTMult(int id) {
    super(id);
  }

  public ASTMult(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b1685759a2bad5969f73a0a1b31ce291 (do not edit this line) */
