/* Generated By:JJTree: Do not edit this line. ASTMethodArguments.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMethodArguments extends SimpleNode {
  public ASTMethodArguments(int id) {
    super(id);
  }

  public ASTMethodArguments(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f6c2d9a7ec8ffd5abc8925146af0e853 (do not edit this line) */
