/* Generated By:JJTree: Do not edit this line. ASTNestedExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTNestedExp extends SimpleNode {
  public ASTNestedExp(int id) {
    super(id);
  }

  public ASTNestedExp(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9be9be827947ff67346b9799bf0ef8af (do not edit this line) */
