/* Generated By:JJTree: Do not edit this line. ASTParameter.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTParameter extends SimpleNode {
  public ASTParameter(int id) {
    super(id);
  }

  public ASTParameter(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=281c869bc954117af94814bd06048112 (do not edit this line) */
