/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

import semantic.*;

public class ASTReturn extends SimpleNode {
  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(Jmm p, int id) {
    super(p, id);
  }

  @Override
  public void checkNodeSemantic() {
    STFunction function = SimpleNode.symbolTable.doesFunctionExist(((ASTMethodDeclaration) this.parent).getName());
    if (function != null) {
      if (!((SimpleNode) this.jjtGetChild(0)).getReturnType().equals(function.getReturn().getType()) ) {
        super.printSemanticError("Return value does not match function signature");
      } 
    }
  }

}
/* JavaCC - OriginalChecksum=ec2190afc24f860c26436397d581ad4b (do not edit this line) */
