/* Generated By:JJTree: Do not edit this line. ASTThis.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTThis extends SimpleNode {
  
  public ASTThis(int id) {
    super(id);
    this.returnType = "this";
  }

  public ASTThis(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=322a4f946530563b6953bb802410381e (do not edit this line) */
