/* Generated By:JJTree: Do not edit this line. ASTTrue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTTrue extends SimpleNode {
  public ASTTrue(int id) {
    super(id);
  }

  public ASTTrue(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3bae5f5f03da761b418ca3ae004e77d3 (do not edit this line) */
