/* Generated By:JJTree: Do not edit this line. ASTThen.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTThen extends SimpleNode {
  public ASTThen(int id) {
    super(id);
  }

  public ASTThen(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1e448a5880f4eec9e8185e5ae129ef42 (do not edit this line) */
