/* Generated By:JJTree&JavaCC: Do not edit this line. JmmConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JmmConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 11;
  /** RegularExpression Id. */
  int EXTENDS = 12;
  /** RegularExpression Id. */
  int PUBLIC = 13;
  /** RegularExpression Id. */
  int STATIC = 14;
  /** RegularExpression Id. */
  int VOID = 15;
  /** RegularExpression Id. */
  int MAIN = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int OB = 21;
  /** RegularExpression Id. */
  int CB = 22;
  /** RegularExpression Id. */
  int OSQB = 23;
  /** RegularExpression Id. */
  int CSQB = 24;
  /** RegularExpression Id. */
  int OPRNT = 25;
  /** RegularExpression Id. */
  int CPRNT = 26;
  /** RegularExpression Id. */
  int CM = 27;
  /** RegularExpression Id. */
  int PNT = 28;
  /** RegularExpression Id. */
  int SCM = 29;
  /** RegularExpression Id. */
  int EQLS = 30;
  /** RegularExpression Id. */
  int NOT = 31;
  /** RegularExpression Id. */
  int AND = 32;
  /** RegularExpression Id. */
  int LS = 33;
  /** RegularExpression Id. */
  int PLS = 34;
  /** RegularExpression Id. */
  int MNS = 35;
  /** RegularExpression Id. */
  int SLSH = 36;
  /** RegularExpression Id. */
  int ASTRSK = 37;
  /** RegularExpression Id. */
  int INT = 38;
  /** RegularExpression Id. */
  int BOOLEAN = 39;
  /** RegularExpression Id. */
  int STRING = 40;
  /** RegularExpression Id. */
  int TRUE = 41;
  /** RegularExpression Id. */
  int FALSE = 42;
  /** RegularExpression Id. */
  int THIS = 43;
  /** RegularExpression Id. */
  int NEW = 44;
  /** RegularExpression Id. */
  int LENGTH = 45;
  /** RegularExpression Id. */
  int IDENTIFIER = 46;
  /** RegularExpression Id. */
  int INTEGERLITERAL = 47;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 8>",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"class\"",
    "\"extends\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"=\"",
    "\"!\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"int\"",
    "\"boolean\"",
    "\"String\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"length\"",
    "<IDENTIFIER>",
    "<INTEGERLITERAL>",
  };

}
