/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 6.0_1 */
package parser;

public interface JmmTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTMAINDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTMETHODARGUMENTS = 5;
  public int JJTRETURN = 6;
  public int JJTMETHODARGUMENT = 7;
  public int JJTVOID = 8;
  public int JJTASSIGN = 9;
  public int JJTARRAYASSIGN = 10;
  public int JJTARRAYINDEX = 11;
  public int JJTWHILE = 12;
  public int JJTIF = 13;
  public int JJTCONDITION = 14;
  public int JJTTHEN = 15;
  public int JJTELSE = 16;
  public int JJTAND = 17;
  public int JJTLESSTHAN = 18;
  public int JJTADDSUB = 19;
  public int JJTMULTDIV = 20;
  public int JJTINTEGERLITERAL = 21;
  public int JJTBOOLEANLITERAL = 22;
  public int JJTIDENTIFIER = 23;
  public int JJTTHIS = 24;
  public int JJTNOT = 25;
  public int JJTLENGTH = 26;
  public int JJTNEW = 27;
  public int JJTCALL = 28;
  public int JJTARGS = 29;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "MethodArguments",
    "Return",
    "MethodArgument",
    "void",
    "Assign",
    "ArrayAssign",
    "ArrayIndex",
    "While",
    "If",
    "Condition",
    "Then",
    "Else",
    "And",
    "LessThan",
    "AddSub",
    "MultDiv",
    "IntegerLiteral",
    "BooleanLiteral",
    "Identifier",
    "This",
    "Not",
    "Length",
    "New",
    "Call",
    "Args",
  };
}
/* JavaCC - OriginalChecksum=2519ea0da75c45cd5186950e4dc7d2d6 (do not edit this line) */
