/* Generated By:JJTree: Do not edit this line. ASTASTFalse.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTASTFalse extends SimpleNode {
  public ASTASTFalse(int id) {
    super(id);
  }

  public ASTASTFalse(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4afc9fdc4946fca01e3d93f241919a73 (do not edit this line) */
