/* Generated By:JJTree: Do not edit this line. ASTASTTrue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTASTTrue extends SimpleNode {
  public ASTASTTrue(int id) {
    super(id);
  }

  public ASTASTTrue(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7ba8fefca412610e50697543401289d1 (do not edit this line) */
