/* Generated By:JJTree: Do not edit this line. ASTArrayIndex.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayIndex extends SimpleNode {
  public ASTArrayIndex(int id) {
    super(id);
  }

  public ASTArrayIndex(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ae56d90d312613d336ee8d5462224f70 (do not edit this line) */
