/* Generated By:JJTree: Do not edit this line. ASTAnd.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAnd extends SimpleNode {
  public ASTAnd(int id) {
    super(id);
  }

  public ASTAnd(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b49cdc56b18d489e3596312bd0c07e0 (do not edit this line) */
