/* Generated By:JJTree: Do not edit this line. ASTASTIdentifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTASTIdentifier extends SimpleNode {
  public ASTASTIdentifier(int id) {
    super(id);
  }

  public ASTASTIdentifier(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3d991d5b644e5700327b9175d926f69 (do not edit this line) */
