/* Generated By:JJTree: Do not edit this line. ASTArrayAssignStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayAssignStatement extends SimpleNode {

  protected String identifier;

  public ASTArrayAssignStatement(int id) {
    super(id);
  }

  public ASTArrayAssignStatement(JmmNew p, int id) {
    super(p, id);
  }

  public String getIdentifier() {
    return this.identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public void dump(String prefix) {
    System.out.println(toString(prefix) + ": " + this.identifier);
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + " ");
        }
      }
    }
  }

}
/* JavaCC - OriginalChecksum=71c8bf3c5d64f63d183317d665f43f7f (do not edit this line) */
