/* Generated By:JJTree: Do not edit this line. ASTASTIntegerLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTASTIntegerLiteral extends SimpleNode {
  public ASTASTIntegerLiteral(int id) {
    super(id);
  }

  public ASTASTIntegerLiteral(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dbee1e3fc2c0bd262523ee187c948943 (do not edit this line) */
