/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAdd extends SimpleNode {
  public ASTAdd(int id) {
    super(id);
  }

  public ASTAdd(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=72489ebc513352de9132e4c00c4fa4ee (do not edit this line) */
