/* Generated By:JJTree: Do not edit this line. ASTCondition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCondition extends SimpleNode {
  public ASTCondition(int id) {
    super(id);
  }

  public ASTCondition(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ecc89de232dc02d668fdb82ff8506049 (do not edit this line) */
