/* Generated By:JJTree: Do not edit this line. ASTDiv.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDiv extends SimpleNode {
  public ASTDiv(int id) {
    super(id);
  }

  public ASTDiv(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d2f4d0e6c8397ba7ff466570f28d5b1b (do not edit this line) */
