/* Generated By:JJTree: Do not edit this line. ASTElseStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElseStatement extends SimpleNode {
  public ASTElseStatement(int id) {
    super(id);
  }

  public ASTElseStatement(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a930c913efce101420a7e78d0136c5df (do not edit this line) */
