/* Generated By:JJTree: Do not edit this line. ASTFalse.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFalse extends SimpleNode {
  public ASTFalse(int id) {
    super(id);
  }

  public ASTFalse(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ee33acbb263d6d85f8f5120a4eef1dcd (do not edit this line) */
