/* Generated By:JJTree: Do not edit this line. ASTLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLiteral extends SimpleNode {
  
  public ASTLiteral(int id) {
    super(id);
  }

  public ASTLiteral(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6c6be3acf465480889c8cfd116f027a0 (do not edit this line) */
