/* Generated By:JJTree: Do not edit this line. ASTLessThan.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLessThan extends SimpleNode {
  public ASTLessThan(int id) {
    super(id);
  }

  public ASTLessThan(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2edc0177dedb372fb668d3c47c0f1750 (do not edit this line) */
