/* Generated By:JJTree: Do not edit this line. ASTLt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLt extends SimpleNode {
  public ASTLt(int id) {
    super(id);
  }

  public ASTLt(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eb1668dc7f7020692a6627585410bafc (do not edit this line) */
