/* Generated By:JJTree: Do not edit this line. ASTLs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLs extends SimpleNode {
  public ASTLs(int id) {
    super(id);
  }

  public ASTLs(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=770e323ab2cd077beb0490a0d9e48719 (do not edit this line) */
