/* Generated By:JJTree: Do not edit this line. ASTLiteralNR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLiteralNR extends SimpleNode {
  public ASTLiteralNR(int id) {
    super(id);
  }

  public ASTLiteralNR(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed52029aaf07c00c2c26f9a373582dd8 (do not edit this line) */
