/* Generated By:JJTree: Do not edit this line. ASTMultDiv.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMultDiv extends SimpleNode {

  protected String op;

  public ASTMultDiv(int id) {
    super(id);
  }

  public ASTMultDiv(JmmNew p, int id) {
    super(p, id);
  }

  public String getOp() {
    return this.op;
  }

  public void setOp(String op){
    this.op = op;
  }

  public void dump(String prefix) {
    System.out.println(toString(prefix) + ": " + this.op);
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + "    ");
        }
      }
    }
  }

}
/* JavaCC - OriginalChecksum=f539d2bff29a7732c5efaf895f056976 (do not edit this line) */
