/* Generated By:JJTree: Do not edit this line. ASTMethodArguments.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodArguments extends SimpleNode {
  public ASTMethodArguments(int id) {
    super(id);
  }

  public ASTMethodArguments(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f13ff73c8e00912f604825bcc3f6cc00 (do not edit this line) */
