/* Generated By:JJTree: Do not edit this line. ASTMultDiv.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMultDiv extends SimpleNode {
  public ASTMultDiv(int id) {
    super(id);
  }

  public ASTMultDiv(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f539d2bff29a7732c5efaf895f056976 (do not edit this line) */
