/* Generated By:JJTree: Do not edit this line. ASTMultDivNR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMultDivNR extends SimpleNode {
  public ASTMultDivNR(int id) {
    super(id);
  }

  public ASTMultDivNR(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a8539e4ccde182c24dca27e09dd2820e (do not edit this line) */
