/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTReturn extends SimpleNode {
  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b7a469595a45a2839d6fdf37a457ecf (do not edit this line) */
