/* Generated By:JJTree: Do not edit this line. ASTThen.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTThen extends SimpleNode {
  public ASTThen(int id) {
    super(id);
  }

  public ASTThen(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=57918b9df7ff41371b084f7d5d85539b (do not edit this line) */
