/* Generated By:JJTree: Do not edit this line. ASTWhileExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileExp extends SimpleNode {
  public ASTWhileExp(int id) {
    super(id);
  }

  public ASTWhileExp(JmmNew p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a833de346c6dc393f883802ff89c628 (do not edit this line) */
