/* Generated By:JJTree&JavaCC: Do not edit this line. JmmConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JmmConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 5;
  /** RegularExpression Id. */
  int EXTENDS = 6;
  /** RegularExpression Id. */
  int OB = 7;
  /** RegularExpression Id. */
  int CB = 8;
  /** RegularExpression Id. */
  int OSQB = 9;
  /** RegularExpression Id. */
  int CSQB = 10;
  /** RegularExpression Id. */
  int SC = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int INTEGER = 14;
  /** RegularExpression Id. */
  int IDENTIFIER = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"class\"",
    "\"extends\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"int\"",
    "\"boolean\"",
    "<INTEGER>",
    "<IDENTIFIER>",
  };

}
