/* Generated By:JavaCC: Do not edit this line. JmmNewTreeConstants.java Version 6.0_1 */
public interface JmmNewTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTMAINDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTMETHODARGUMENTS = 5;
  public int JJTRETURN = 6;
  public int JJTMETHODARGUMENT = 7;
  public int JJTVOID = 8;
  public int JJTASSIGN = 9;
  public int JJTARRAYASSIGN = 10;
  public int JJTARRAYINDEX = 11;
  public int JJTWHILE = 12;
  public int JJTIF = 13;
  public int JJTCONDITION = 14;
  public int JJTTHEN = 15;
  public int JJTELSE = 16;
  public int JJTAND = 17;
  public int JJTLESSTHAN = 18;
  public int JJTADDSUB = 19;
  public int JJTMULTDIV = 20;
  public int JJTINTEGERLITERAL = 21;
  public int JJTIDENTIFIER = 22;
  public int JJTNEW = 23;
  public int JJTCALL = 24;
  public int JJTARGS = 25;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "MethodArguments",
    "Return",
    "MethodArgument",
    "void",
    "Assign",
    "ArrayAssign",
    "ArrayIndex",
    "While",
    "If",
    "Condition",
    "Then",
    "Else",
    "And",
    "LessThan",
    "AddSub",
    "MultDiv",
    "IntegerLiteral",
    "Identifier",
    "New",
    "Call",
    "Args",
  };
}
/* JavaCC - OriginalChecksum=4aacd607693b2e50927c82e42d43db1a (do not edit this line) */
