/* Generated By:JavaCC: Do not edit this line. JmmNewTreeConstants.java Version 6.0_1 */
public interface JmmNewTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTMAINDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTMETHODARGUMENTS = 5;
  public int JJTRETURN = 6;
  public int JJTMETHODARGUMENT = 7;
  public int JJTIDENTIFIER = 8;
  public int JJTTYPE = 9;
  public int JJTVOID = 10;
  public int JJTIFSTATEMENT = 11;
  public int JJTWHILESTATEMENT = 12;
  public int JJTASSIGNSTATEMENT = 13;
  public int JJTARRAYASSIGNSTATEMENT = 14;
  public int JJTARRAYINDEX = 15;
  public int JJTEXPRESSION = 16;
  public int JJTAND = 17;
  public int JJTLESSTHAN = 18;
  public int JJTADDSUB = 19;
  public int JJTMULTDIV = 20;
  public int JJTINTEGERLITERAL = 21;
  public int JJTCALL = 22;
  public int JJTARGS = 23;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "MethodArguments",
    "Return",
    "MethodArgument",
    "Identifier",
    "Type",
    "void",
    "IfStatement",
    "WhileStatement",
    "AssignStatement",
    "ArrayAssignStatement",
    "ArrayIndex",
    "Expression",
    "And",
    "LessThan",
    "AddSub",
    "MultDiv",
    "IntegerLiteral",
    "Call",
    "Args",
  };
}
/* JavaCC - OriginalChecksum=79ec3a2fab5fce4c33ab653bf6b3d785 (do not edit this line) */
