/* Generated By:JavaCC: Do not edit this line. JmmNewTreeConstants.java Version 6.0_1 */
public interface JmmNewTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTMAINDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTMETHODARGUMENTS = 5;
  public int JJTRETURN = 6;
  public int JJTMETHODARGUMENT = 7;
  public int JJTIDENTIFIER = 8;
  public int JJTTYPE = 9;
  public int JJTSTATEMENT = 10;
  public int JJTVOID = 11;
  public int JJTEXPRESSION = 12;
  public int JJTAND = 13;
  public int JJTLESSTHAN = 14;
  public int JJTADDSUB = 15;
  public int JJTMULTDIV = 16;
  public int JJTINTEGERLITERAL = 17;
  public int JJTCALL = 18;
  public int JJTARGS = 19;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "MethodArguments",
    "Return",
    "MethodArgument",
    "Identifier",
    "Type",
    "Statement",
    "void",
    "Expression",
    "And",
    "LessThan",
    "AddSub",
    "MultDiv",
    "IntegerLiteral",
    "Call",
    "Args",
  };
}
/* JavaCC - OriginalChecksum=4556b874d50d8c1e79611340124d5a7a (do not edit this line) */
