/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 6.0_1 */
public interface JmmTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
  };
}
/* JavaCC - OriginalChecksum=2b40780b35e6759921ff2a81a6e5f2bf (do not edit this line) */
