/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 6.0_1 */
public interface JmmTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTMAINDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTTYPE = 5;
  public int JJTSTATEMENT = 6;
  public int JJTEXPRESSION = 7;
  public int JJTNREXPRESSION = 8;
  public int JJTVOID = 9;
  public int JJTADD = 10;
  public int JJTSUB = 11;
  public int JJTMUL = 12;
  public int JJTDIV = 13;
  public int JJTTERM = 14;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "Type",
    "Statement",
    "Expression",
    "NRExpression",
    "void",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Term",
  };
}
/* JavaCC - OriginalChecksum=65942ce7e30efd57e9f8479d4c5ac4fd (do not edit this line) */
